---
- name: hosts file generate
  hosts: all
  become: yes
  tasks:
    - name: implement template
      template: 
        src: hosts.j2
        dest: /root/myhosts
      when: '"dev" in group_names'
