---
- name: specification report
  hosts: all
  become: yes
  tasks:
    - name: copy spec.empty
      copy:
        src: specs.empty
        dest: /root/specs.txt
    - name:
      lineinfile:
        path: /root/specs.txt
        regexp: ^HOST=
        line: HOST="{{ ansible_hostname }}"
        state: present
    - name:
      lineinfile:
        path: /root/specs.txt
        regexp: ^MEMORY=
        line: MEMORY="{{ ansible_memtotal_mb }}"
        state: present
    - name:
      lineinfile:
        path: /root/specs.txt
        regexp: '^VDA_DISK_SIZE='
        line: 'VDA_DISK_SIZE={% if ansible_devices.vda is defined %}{{ansible_devices.vda.size}}{%else%}NONE{%endif%}'
        state: present
    - name:
      lineinfile:
        path: /root/specs.txt
        regexp: '^VDB_DISK_SIZE='
        line: 'VDB_DISK_SIZE={% if ansible_devices.vdb is defined %}{{ansible_devices.vdb.size}}{%else%}NONE{%endif%}'
        state: present 

